### ISSUE TITLE
Integrate internal code style guide into repository.

### ISSUE THREAD

**Issue by wtrocki** [fheng/best_practice#5]
Internal guide was created here: 

https://github.com/fheng/help/blob/master/code-style.md

It would be better to move it to one place. @maleck13 WDYT?

**Comment by maleck13** [comment]
@wtrocki Makes sense to me to add it here and link to this location from the help repo. @grdryn was behind the doc so would be good to get his thoughts.

**Comment by grdryn** [comment]
@maleck13 I think @jasonmadigan and @lgriffin were behind it. I just put some additional stuff in there :)

**Comment by wtrocki** [comment]
https://github.com/fheng/best_practice/pull/6
